client: 5

round: 10

training:
  batch_size: 64
  learning_rate: 0.01

data:
  dataset_path: "UCI_Credit_Card.csv"
  smote: false
  rus: false
  scale: true
  encode: true
  pca: 0
  kbest: false
  batch_size: 64

aggregation:
  method: FedAvg

server:
  address: "127.0.0.1:8080"

model:
  C: 10
  class_weight: 'balanced'
  max_iter: 1000
  dual: false